name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platame/snk@master
        id: snake-gif
        with:
          github_user_name: kolansky-developer
          svg_out_path: dist/github-github-pages@v2.1.3

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITBUB_TOKEN: ${{ screts.GITHUB_TOKEN }}
